server:
  port: 4000

spring:
    mvc:
      pathmatch:
            matching-strategy: ant_path_matcher
    
       
       
    datasource:
      url: jdbc:mysql://localhost:3306/olxloginApp
      username: root
      password: root 
    jpa:
      properties:
        hibernate:
             format_sql: true
      hibernate:
         ddl-auto: update 
      show-sql: true     

      
management:
   endpoints:
     web:
       exposure:
          include:
           - "*"  
          exclude:
          
       base-path: "/my-actuator"     